### ISSUE TITLE
Rendering HTML Views

### ISSUE THREAD

**Issue by s2t2** [DronRathore/goexpress#24]
Hi, I was wondering if it is possible to use this library to render an HTML view file at a given path. And if so, how?

**Comment by s2t2** [comment]
I guess the desired usage would be something like:

```go
app.Get("/hello", func(req *request.Request, res *response.Response, next func()){
	   res.Render("./views/hello.html", false)
  })
```

**Comment by AlexNodex** [comment]
This isn’t really a twig bug.

Rendering the html to a file is trivial because the render method returns a string 

Please use places like stack overflow for usage issues and GitHub for bugs and genuine issues

**Comment by AlexNodex** [comment]
Apologies for my last comment, I was in the wrong repo!

**Comment by DronRathore** [comment]
Hey @s2t2, apologies for delayed response, I think i didn't quite get you, do you want to pass dynamic options to the html or you just want to send the HTML response?
You can use ```res.Send``` to send an HTML file by passing a [file path](https://github.com/DronRathore/goexpress/blob/master/response/response.go#L115).

But would be a good feature though to support this, I may work on this one on a weekend, I am thinking of letting render function take options too so that you can render dynamic content.
